marklogic/demo-cat

- rest-api/config/options/all.xml
- ui/app/search/results-dir.html
- ui/app/styles/main.less
- ui/app/views/demo.html
Please pull in the latest changes.
> updating the UI for issue #120 and #118

- bower.json
- ui/app/search/search-ctrl.js
Upgraded ml-search-ng and removed a couple of patches for ml-search-ng that fixed faceting.
> Upgrade ml-search-ng

- ui/app/index.ejs
- ui/app/search/search.html
- ui/app/styles/main.less
I had a request to add more panels per a row.
> widening the content area to get 3 across

- ui/app/styles/main.less
- ui/app/views/demo.html
I added in changes to the detail page. It now has panels on the left side.
> changing layout of the details page

- rest-api/config/options/all.xml
- ui/app/scripts/controllers/create.js
- ui/app/search/results-dir.html
- ui/app/views/create.html
- ui/app/views/demo.html
Included Jen’s styling for showing search results with restrictions.
Updated the create/edit display to flag a demo as restricted and a box
for adding restriction details.  Updated demo details page to show
restriction info when it is present in the document.
> #3 - Restrictions Capability Added

- ui/app/index.ejs
- ui/app/search/results-dir.html
- ui/app/search/search.html
- ui/app/styles/login.less
- ui/app/styles/main.less
This is the fix for the responsive stacking of the panels in smaller views.
> Fix for #141.

- ui/app/styles/main.less
Please pull in this change to fix the number of tiles for tablets.
> #141 changing the number of tiles

- rest-api/config/options/all.xml
- ui/app/search/results-dir.html
- ui/app/search/search.js
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
short desc changes for develop branch
> Issue #133 - provide short description

- ui/app/scripts/controllers/create.js
- ui/app/views/create.html
> enforces required input types in /create form

- bower.json
- ui/app/scripts/controllers/create.js
- ui/app/views/create.html
PR that was merged yesterday looked good initially, but then I noticed both input and button were showing file dialog, and attachments weren't shown consistently. Upgrading to latest version, and getting rid of Attach button fixed this..
> Bugfix for #2: old version for angular-file-upload behaved badly

- ui/app/styles/main.less
- ui/app/views/modals/edit-memo.html
Can you please pull in the fix for #172? thank you!
> fixes for #172 - editing the edit-memo modal

- ui/app/styles/main.less
- ui/app/views/create.html
updated with changes we discussed yesterday. moved around the items and added headers.
> updating the create.html file with changes discussed with Geert.

- ui/app/styles/main.less
- ui/app/views/create.html
These are small design edits for the create.html page based on my emails with Geert.
> Small design edits

- ui/app/scripts/directives/autocomplete.html
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
This is the changes we reviewed over Skype.
> added ui mods per discussion with Geert

- ui/app/scripts/directives/add-comment.html
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
These are additional minor edits from conversations with @grtjn.
> Minor UI edits

- deploy/app_specific.rb
- deploy/ml-config.xml
- migration.md
- rest-api/config/options/all.xml
- src/data-migration/add-credentials.xqy
- src/data-migration/host-to-url.xqy
- src/data-migration/maintainer-to-tech-contact.xqy
- src/transform/to-json.xqy
- src/triggers/add-change-tracking.xqy
Fixed some data migration issues, and implements #93 including automatic change tracking within the database.
> Sorting by date

- README.mdown
I added the ./ to the README per the request of our users.
> adding the ./ to the ml commands for ease of use

- deploy/app_specific.rb
- deploy/build.properties
- deploy/ml-config.xml
- rest-api/config/options/all.xml
- rest-api/ext/comment.xqy
- rest-api/ext/file-bug.xqy
- rest-api/ext/follow.xqy
- rest-api/ext/profile.xqy
- rest-api/ext/user-list.xqy
- rest-api/ext/version.xqy
- server.js
- src/alerting/alert-demo-broken-action.xqy
- src/alerting/alert-send-demo-email.xqy
- src/app/config/config.xqy
- src/data-migration/add-credentials.xqy
- src/data-migration/host-to-url.xqy
- src/data-migration/maintainer-to-tech-contact.xqy
- src/lib/demo-model.xqy
- src/lib/user-model.xqy
- src/lib/utilities.xqy
- src/triggers/add-change-tracking.xqy
- ui/app/scripts/controllers/create.js
- ui/app/scripts/controllers/demo.js
- ui/app/scripts/controllers/profile.js
- ui/app/search/facets-dir.html
- ui/app/search/search-ctrl.js
- ui/app/styles/main.less
- ui/app/views/demo.html
- ui/app/views/profile.html
stacks on top of #194, merge that first. All work concentrated in last commit..
> Demo model abstraction

- rest-api/ext/analyze-data.xqy
- server.js
- src/robots.txt
- ui/app/auth/auth-srv.js
- ui/app/robots.txt
- ui/app/scripts/controllers/create.js
- ui/app/search/results-dir.html
- ui/app/search/search.js
- ui/app/views/create.html
- ui/app/views/login.html
Note: I already pushed these changes onto catalog-new for review.
> Various changes

- server.js
- ui/app/auth/auth-srv.js
- ui/app/scripts/app.js
This will resolve the infinite loop and I believe the it will prevent the random logging out.
> #196 infinite authentication loop

- README.mdown
- rest-api/ext/follow.xqy
- ui/app/header/header-ctrl.js
- ui/app/home/home.html
- ui/app/index.ejs
- ui/app/scripts/controllers/demo.js
- ui/app/scripts/services/modal.service.js
- ui/app/styles/header.less
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
- ui/app/views/header/header.html
- ui/app/views/header/ml-input-fa.html
- ui/app/views/modals/help.html
> Docs on HTTPS, UI changes, fixed follow

- README.mdown
- deploy/app_specific.rb
- deploy/ml-config.xml
- rest-api/config/options/all.xml
- server.js
- src/lib/demo-model.xqy
- src/lib/utilities.xqy
- ui/app/home/home-ctrl.js
- ui/app/home/home.html
- ui/app/index.ejs
- ui/app/scripts/controllers/create.js
- ui/app/search/ml-search-ng.js
- ui/app/search/results-dir.html
- ui/app/styles/homepage.less
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
- ui/app/views/header/header.html
- ui/app/views/modals/edit-dont-touch.html
- ui/app/views/modals/edit-spotlight.html
- ui/app/views/modals/edit-vanguard.html
- updated docs to install https cert
- send CC to vanguard for bugs and broken demo alerts
- updated copyright year
- suppressed assignee for bugs
- made restrictionDetails required
- fixed issue with displaying selected facets
- fixed #211 timezone support for don't touch section
- wildcarded search
- default suggestions on full db word lexicon
- show all demos button
- and a few more UI tidbits..
> Processed feedback from Sid

- ui/app/views/modals/help.html
Already pushed to server (yesterday)..
> Last minute Q-n-A update

- ui/app/styles/homepage.less
- ui/app/styles/main.less
- ui/app/views/modals/edit-dont-touch.html
This is a css fix for the spacing.
> fixing spacing for #216

- deploy/app_specific.rb
- deploy/ml-config.xml
- rest-api/ext/profile.xqy
- server.js
- src/lib/demo-model.xqy
- src/lib/user-model.xqy
- src/triggers/add-change-tracking.xqy
- ui/app/scripts/controllers/profile.js
- ui/app/styles/main.less
- ui/app/views/profile.html
* Fixed #223, comment as reader
* Allowed follow, and profile update as reader
* Added presales to writer role
* Small UI fix for 'restricted' demo title in search
> Allow specific updates to reader role

- bower.json
- ui/app/index.ejs
- ui/app/scripts/app.js
- ui/app/scripts/controllers/demo.js
- ui/app/scripts/services/modal.service.js
- ui/app/styles/main.less
- ui/app/views/create.html
- ui/app/views/demo.html
- ui/app/views/modals/show-media.html
This fixes an issue with YouTube videos being broken.
> Fix issue with YouTube embeds

- ui/app/scripts/controllers/create.js
- ui/app/views/create.html
> Fixed #241: increased upload limit from 5 to 10 mb

- data/initial-quick-filter-config.json
- ui/app/search/search-ctrl.js
- ui/app/search/search.html
#246 - added dynamic list of checkboxes that allow adding structured queries to the additional query for the search.
> #246 - added dynamic list of checkboxes

- data/config/quick-filter.json
- deploy/ml-config.xml
- ui/app/search/search.html
- ui/app/styles/main.less
> Refinements for #246

- README.mdown
- deploy/app_specific.rb
- deploy/ml-config.xml
- etc/init.d/node-express-service
- etc/init.d/node-gulp-service
- ui/app/home/home.html
- ui/app/search/ml-search-ng.js
- ui/app/search/search-ctrl.js
- ui/app/views/modals/edit-vanguard.html
> Fixed #256: revised search-ctrl init logic, allowed relative url in News section

- server.js
This fixes an TCP duplicate acknowledgement issue with the proxy to MarkLogic that was causing weird entries in the ML access log.
> Fix bad calls MarkLogic caused by proxy

- deploy/app_specific.rb
- src/triggers/add-converted-attachment.xqy
- ui/app/scripts/controllers/create.js
- ui/app/views/demo.html
- ui/app/views/modals/show-memo.html
@grtjn Please review. Let me know if I also need to add the filtered content to be visible in the UI when searching or detail view.
> add filtered content from attachment to document
